As statment prac try catch std:exception